/**
 * Static plant database: ~80 permaculture plants across 4 climates.
 * Each plant has companions/antagonists for guild building.
 */

import type { ClimateType } from '$lib/types';

export interface Plant {
	id: string;
	name: string;
	scientificName: string;
	category: 'tree' | 'shrub' | 'herb' | 'groundcover' | 'vine' | 'root' | 'grass';
	layer: 'canopy' | 'understory' | 'shrub' | 'herbaceous' | 'groundcover' | 'root' | 'vine';
	climates: ClimateType[];
	companions: string[]; // plant IDs that grow well together
	antagonists: string[]; // plant IDs to keep separate
	spacing: number; // meters between plants
	harvestMonths?: number[]; // 1-12
	edible: boolean;
	nitrogenFixer: boolean;
	dynamicAccumulator: boolean;
	notes: string;
}

export const plants: Plant[] = [
	// ===== CANOPY TREES =====
	{ id: 'apple', name: 'Apple', scientificName: 'Malus domestica', category: 'tree', layer: 'canopy', climates: ['temperate', 'subtropical'], companions: ['comfrey', 'chives', 'nasturtium', 'clover', 'borage'], antagonists: ['walnut'], spacing: 5, harvestMonths: [8, 9, 10], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Needs chill hours. Central guild tree.' },
	{ id: 'pear', name: 'Pear', scientificName: 'Pyrus communis', category: 'tree', layer: 'canopy', climates: ['temperate', 'subtropical'], companions: ['comfrey', 'clover', 'tansy'], antagonists: ['walnut'], spacing: 5, harvestMonths: [8, 9, 10], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Long-lived. Good pollinator pair with apple.' },
	{ id: 'peach', name: 'Peach', scientificName: 'Prunus persica', category: 'tree', layer: 'canopy', climates: ['temperate', 'subtropical'], companions: ['garlic', 'tansy', 'comfrey'], antagonists: ['tomato'], spacing: 4, harvestMonths: [6, 7, 8], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Needs well-drained soil. Self-fertile varieties available.' },
	{ id: 'plum', name: 'Plum', scientificName: 'Prunus domestica', category: 'tree', layer: 'canopy', climates: ['temperate', 'subtropical'], companions: ['comfrey', 'garlic', 'clover'], antagonists: [], spacing: 4, harvestMonths: [7, 8], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Many varieties. Some self-fertile.' },
	{ id: 'fig', name: 'Fig', scientificName: 'Ficus carica', category: 'tree', layer: 'canopy', climates: ['subtropical', 'temperate', 'arid'], companions: ['comfrey', 'mint', 'nasturtium'], antagonists: [], spacing: 4, harvestMonths: [6, 7, 8, 9], edible: true, nitrogenFixer: false, dynamicAccumulator: true, notes: 'Drought-tolerant once established. Deep roots.' },
	{ id: 'mango', name: 'Mango', scientificName: 'Mangifera indica', category: 'tree', layer: 'canopy', climates: ['tropical', 'subtropical'], companions: ['turmeric', 'ginger', 'lemongrass'], antagonists: [], spacing: 8, harvestMonths: [5, 6, 7], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Large canopy. Excellent shade tree.' },
	{ id: 'avocado', name: 'Avocado', scientificName: 'Persea americana', category: 'tree', layer: 'canopy', climates: ['tropical', 'subtropical'], companions: ['comfrey', 'sweet-potato', 'banana'], antagonists: [], spacing: 6, harvestMonths: [2, 3, 4, 5], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Needs good drainage. Type A + B for pollination.' },
	{ id: 'citrus-orange', name: 'Orange', scientificName: 'Citrus sinensis', category: 'tree', layer: 'canopy', climates: ['subtropical', 'tropical'], companions: ['comfrey', 'nasturtium', 'borage'], antagonists: [], spacing: 5, harvestMonths: [11, 12, 1, 2], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Evergreen. Good windbreak understory.' },
	{ id: 'citrus-lemon', name: 'Lemon', scientificName: 'Citrus limon', category: 'tree', layer: 'canopy', climates: ['subtropical', 'tropical', 'arid'], companions: ['comfrey', 'basil', 'nasturtium'], antagonists: [], spacing: 4, harvestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Year-round harvest. Frost-sensitive.' },
	{ id: 'moringa', name: 'Moringa', scientificName: 'Moringa oleifera', category: 'tree', layer: 'canopy', climates: ['tropical', 'subtropical', 'arid'], companions: ['sweet-potato', 'pigeon-pea'], antagonists: [], spacing: 3, harvestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], edible: true, nitrogenFixer: false, dynamicAccumulator: true, notes: 'Fast-growing. Leaves, pods, flowers all edible.' },
	{ id: 'walnut', name: 'Walnut', scientificName: 'Juglans regia', category: 'tree', layer: 'canopy', climates: ['temperate'], companions: ['elderberry', 'mulberry'], antagonists: ['apple', 'pear', 'tomato', 'blueberry'], spacing: 10, harvestMonths: [9, 10], edible: true, nitrogenFixer: false, dynamicAccumulator: true, notes: 'Produces juglone. Keep away from sensitive plants.' },
	{ id: 'mulberry', name: 'Mulberry', scientificName: 'Morus alba', category: 'tree', layer: 'canopy', climates: ['temperate', 'subtropical', 'tropical'], companions: ['comfrey', 'clover'], antagonists: [], spacing: 6, harvestMonths: [5, 6, 7], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Prolific fruit. Good chicken forage tree.' },
	{ id: 'olive', name: 'Olive', scientificName: 'Olea europaea', category: 'tree', layer: 'canopy', climates: ['arid', 'subtropical', 'temperate'], companions: ['lavender', 'rosemary', 'thyme'], antagonists: [], spacing: 6, harvestMonths: [10, 11, 12], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Extremely drought-tolerant. Long-lived.' },
	{ id: 'coconut', name: 'Coconut Palm', scientificName: 'Cocos nucifera', category: 'tree', layer: 'canopy', climates: ['tropical'], companions: ['banana', 'sweet-potato', 'taro'], antagonists: [], spacing: 8, harvestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Coastal. Year-round harvest.' },
	{ id: 'jackfruit', name: 'Jackfruit', scientificName: 'Artocarpus heterophyllus', category: 'tree', layer: 'canopy', climates: ['tropical', 'subtropical'], companions: ['banana', 'ginger'], antagonists: [], spacing: 8, harvestMonths: [3, 4, 5, 6], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Largest tree-borne fruit. Shade tree.' },

	// ===== UNDERSTORY TREES =====
	{ id: 'banana', name: 'Banana', scientificName: 'Musa spp.', category: 'tree', layer: 'understory', climates: ['tropical', 'subtropical'], companions: ['sweet-potato', 'taro', 'comfrey', 'lemongrass'], antagonists: [], spacing: 3, harvestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], edible: true, nitrogenFixer: false, dynamicAccumulator: true, notes: 'Fast-growing. Great mulch source from leaves.' },
	{ id: 'papaya', name: 'Papaya', scientificName: 'Carica papaya', category: 'tree', layer: 'understory', climates: ['tropical', 'subtropical'], companions: ['banana', 'sweet-potato'], antagonists: [], spacing: 3, harvestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Short-lived but fast. Fruits in first year.' },
	{ id: 'elderberry', name: 'Elderberry', scientificName: 'Sambucus nigra', category: 'tree', layer: 'understory', climates: ['temperate', 'subtropical'], companions: ['comfrey', 'clover'], antagonists: [], spacing: 3, harvestMonths: [8, 9], edible: true, nitrogenFixer: false, dynamicAccumulator: true, notes: 'Berries and flowers used. Medicinal.' },
	{ id: 'pomegranate', name: 'Pomegranate', scientificName: 'Punica granatum', category: 'tree', layer: 'understory', climates: ['arid', 'subtropical', 'temperate'], companions: ['lavender', 'rosemary'], antagonists: [], spacing: 3, harvestMonths: [9, 10, 11], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Drought-tolerant. Beautiful flowers.' },
	{ id: 'guava', name: 'Guava', scientificName: 'Psidium guajava', category: 'tree', layer: 'understory', climates: ['tropical', 'subtropical'], companions: ['banana', 'comfrey'], antagonists: [], spacing: 4, harvestMonths: [3, 4, 5, 6, 7], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Prolific fruiter. Good for hedgerows.' },

	// ===== SHRUBS =====
	{ id: 'blueberry', name: 'Blueberry', scientificName: 'Vaccinium corymbosum', category: 'shrub', layer: 'shrub', climates: ['temperate'], companions: ['strawberry', 'clover', 'fern'], antagonists: ['walnut'], spacing: 1.5, harvestMonths: [6, 7, 8], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Needs acid soil (pH 4.5-5.5). Mulch heavily.' },
	{ id: 'raspberry', name: 'Raspberry', scientificName: 'Rubus idaeus', category: 'shrub', layer: 'shrub', climates: ['temperate'], companions: ['garlic', 'tansy', 'comfrey'], antagonists: ['blackberry'], spacing: 0.6, harvestMonths: [6, 7, 8], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Spreads by suckers. Trellis recommended.' },
	{ id: 'blackberry', name: 'Blackberry', scientificName: 'Rubus fruticosus', category: 'shrub', layer: 'shrub', climates: ['temperate', 'subtropical'], companions: ['comfrey', 'tansy'], antagonists: ['raspberry'], spacing: 1, harvestMonths: [7, 8, 9], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Vigorous. Can become invasive if not managed.' },
	{ id: 'currant', name: 'Currant', scientificName: 'Ribes spp.', category: 'shrub', layer: 'shrub', climates: ['temperate'], companions: ['comfrey', 'garlic'], antagonists: [], spacing: 1.5, harvestMonths: [6, 7], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Shade-tolerant. Good understory shrub.' },
	{ id: 'gooseberry', name: 'Gooseberry', scientificName: 'Ribes uva-crispa', category: 'shrub', layer: 'shrub', climates: ['temperate'], companions: ['comfrey', 'tansy'], antagonists: [], spacing: 1.5, harvestMonths: [6, 7], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Thorny. Good barrier plant.' },
	{ id: 'rosemary', name: 'Rosemary', scientificName: 'Salvia rosmarinus', category: 'shrub', layer: 'shrub', climates: ['temperate', 'subtropical', 'arid'], companions: ['sage', 'lavender', 'thyme', 'carrot'], antagonists: [], spacing: 0.8, edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Drought-tolerant. Pest-repellent.' },
	{ id: 'lavender', name: 'Lavender', scientificName: 'Lavandula angustifolia', category: 'shrub', layer: 'shrub', climates: ['temperate', 'arid', 'subtropical'], companions: ['rosemary', 'sage', 'olive'], antagonists: [], spacing: 0.6, edible: false, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Pollinator magnet. Deer-resistant.' },
	{ id: 'pigeon-pea', name: 'Pigeon Pea', scientificName: 'Cajanus cajan', category: 'shrub', layer: 'shrub', climates: ['tropical', 'subtropical', 'arid'], companions: ['moringa', 'banana', 'sweet-potato'], antagonists: [], spacing: 1.5, harvestMonths: [9, 10, 11], edible: true, nitrogenFixer: true, dynamicAccumulator: false, notes: 'Nitrogen fixer. Chop-and-drop mulch.' },
	{ id: 'katuk', name: 'Katuk', scientificName: 'Sauropus androgynus', category: 'shrub', layer: 'shrub', climates: ['tropical', 'subtropical'], companions: ['banana', 'taro'], antagonists: [], spacing: 1, harvestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Perennial leaf vegetable. Shade-tolerant.' },

	// ===== HERBS (Herbaceous layer) =====
	{ id: 'comfrey', name: 'Comfrey', scientificName: 'Symphytum officinale', category: 'herb', layer: 'herbaceous', climates: ['temperate', 'subtropical'], companions: ['apple', 'pear', 'fig', 'banana'], antagonists: [], spacing: 0.6, edible: false, nitrogenFixer: false, dynamicAccumulator: true, notes: 'Premier dynamic accumulator. Chop-and-drop mulch 4-5x/year.' },
	{ id: 'borage', name: 'Borage', scientificName: 'Borago officinalis', category: 'herb', layer: 'herbaceous', climates: ['temperate', 'subtropical'], companions: ['strawberry', 'tomato', 'apple'], antagonists: [], spacing: 0.4, harvestMonths: [5, 6, 7, 8], edible: true, nitrogenFixer: false, dynamicAccumulator: true, notes: 'Self-seeds. Excellent bee plant.' },
	{ id: 'basil', name: 'Basil', scientificName: 'Ocimum basilicum', category: 'herb', layer: 'herbaceous', climates: ['temperate', 'subtropical', 'tropical'], companions: ['tomato', 'pepper', 'citrus-lemon'], antagonists: ['sage'], spacing: 0.3, harvestMonths: [6, 7, 8, 9], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Annual in temperate. Repels flies and mosquitoes.' },
	{ id: 'mint', name: 'Mint', scientificName: 'Mentha spp.', category: 'herb', layer: 'herbaceous', climates: ['temperate', 'subtropical', 'tropical'], companions: ['tomato', 'cabbage', 'fig'], antagonists: [], spacing: 0.3, edible: true, nitrogenFixer: false, dynamicAccumulator: true, notes: 'Vigorous spreader. Contain in pots or borders.' },
	{ id: 'chives', name: 'Chives', scientificName: 'Allium schoenoprasum', category: 'herb', layer: 'herbaceous', climates: ['temperate', 'subtropical'], companions: ['apple', 'carrot', 'tomato'], antagonists: ['beans'], spacing: 0.2, harvestMonths: [3, 4, 5, 6, 7, 8, 9, 10], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Pest-repellent. Good border plant.' },
	{ id: 'garlic', name: 'Garlic', scientificName: 'Allium sativum', category: 'herb', layer: 'herbaceous', climates: ['temperate', 'subtropical'], companions: ['peach', 'raspberry', 'tomato', 'rose'], antagonists: ['beans', 'peas'], spacing: 0.15, harvestMonths: [6, 7], edible: true, nitrogenFixer: false, dynamicAccumulator: true, notes: 'Plant in autumn. Fungal disease suppressor.' },
	{ id: 'sage', name: 'Sage', scientificName: 'Salvia officinalis', category: 'herb', layer: 'herbaceous', climates: ['temperate', 'arid', 'subtropical'], companions: ['rosemary', 'thyme', 'carrot', 'cabbage'], antagonists: ['basil'], spacing: 0.4, edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Drought-tolerant once established.' },
	{ id: 'thyme', name: 'Thyme', scientificName: 'Thymus vulgaris', category: 'herb', layer: 'herbaceous', climates: ['temperate', 'arid', 'subtropical'], companions: ['rosemary', 'sage', 'cabbage', 'strawberry'], antagonists: [], spacing: 0.3, edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Excellent groundcover. Bee plant.' },
	{ id: 'dill', name: 'Dill', scientificName: 'Anethum graveolens', category: 'herb', layer: 'herbaceous', climates: ['temperate', 'subtropical'], companions: ['cabbage', 'cucumber', 'lettuce'], antagonists: ['carrot'], spacing: 0.3, harvestMonths: [6, 7, 8], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Attracts beneficial insects. Self-seeds.' },
	{ id: 'parsley', name: 'Parsley', scientificName: 'Petroselinum crispum', category: 'herb', layer: 'herbaceous', climates: ['temperate', 'subtropical'], companions: ['tomato', 'carrot', 'chives'], antagonists: ['lettuce'], spacing: 0.2, harvestMonths: [4, 5, 6, 7, 8, 9, 10], edible: true, nitrogenFixer: false, dynamicAccumulator: true, notes: 'Biennial. Attracts swallowtail butterflies.' },
	{ id: 'nasturtium', name: 'Nasturtium', scientificName: 'Tropaeolum majus', category: 'herb', layer: 'herbaceous', climates: ['temperate', 'subtropical', 'tropical'], companions: ['apple', 'tomato', 'cucumber', 'beans'], antagonists: [], spacing: 0.3, harvestMonths: [6, 7, 8, 9], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Trap crop for aphids. Flowers and leaves edible.' },
	{ id: 'tansy', name: 'Tansy', scientificName: 'Tanacetum vulgare', category: 'herb', layer: 'herbaceous', climates: ['temperate'], companions: ['raspberry', 'blackberry', 'pear', 'peach'], antagonists: [], spacing: 0.4, edible: false, nitrogenFixer: false, dynamicAccumulator: true, notes: 'Insect repellent. Potassium accumulator.' },
	{ id: 'lemongrass', name: 'Lemongrass', scientificName: 'Cymbopogon citratus', category: 'herb', layer: 'herbaceous', climates: ['tropical', 'subtropical'], companions: ['mango', 'banana', 'citrus-lemon'], antagonists: [], spacing: 0.6, edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Mosquito repellent. Culinary herb.' },
	{ id: 'turmeric', name: 'Turmeric', scientificName: 'Curcuma longa', category: 'herb', layer: 'herbaceous', climates: ['tropical', 'subtropical'], companions: ['ginger', 'mango', 'banana'], antagonists: [], spacing: 0.3, harvestMonths: [10, 11], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Shade-tolerant. Good under fruit trees.' },
	{ id: 'ginger', name: 'Ginger', scientificName: 'Zingiber officinale', category: 'herb', layer: 'herbaceous', climates: ['tropical', 'subtropical'], companions: ['turmeric', 'banana', 'jackfruit'], antagonists: [], spacing: 0.3, harvestMonths: [10, 11, 12], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Shade-loving. Perfect under canopy.' },
	{ id: 'oregano', name: 'Oregano', scientificName: 'Origanum vulgare', category: 'herb', layer: 'herbaceous', climates: ['temperate', 'arid', 'subtropical'], companions: ['pepper', 'tomato', 'beans'], antagonists: [], spacing: 0.3, edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Drought-tolerant. Good groundcover.' },
	{ id: 'cilantro', name: 'Cilantro / Coriander', scientificName: 'Coriandrum sativum', category: 'herb', layer: 'herbaceous', climates: ['temperate', 'subtropical', 'tropical'], companions: ['tomato', 'beans', 'dill'], antagonists: [], spacing: 0.15, harvestMonths: [4, 5, 6, 7, 8], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Bolts in heat. Successive sowing recommended.' },
	{ id: 'fennel', name: 'Fennel', scientificName: 'Foeniculum vulgare', category: 'herb', layer: 'herbaceous', climates: ['temperate', 'subtropical', 'arid'], companions: [], antagonists: ['tomato', 'beans', 'carrot'], spacing: 0.4, harvestMonths: [7, 8, 9], edible: true, nitrogenFixer: false, dynamicAccumulator: true, notes: 'Allelopathic — plant alone or at borders.' },

	// ===== VEGETABLES (Herbaceous) =====
	{ id: 'tomato', name: 'Tomato', scientificName: 'Solanum lycopersicum', category: 'herb', layer: 'herbaceous', climates: ['temperate', 'subtropical', 'tropical'], companions: ['basil', 'carrot', 'nasturtium', 'parsley', 'chives'], antagonists: ['fennel', 'walnut', 'peach'], spacing: 0.5, harvestMonths: [7, 8, 9, 10], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Heavy feeder. Needs staking.' },
	{ id: 'pepper', name: 'Pepper', scientificName: 'Capsicum annuum', category: 'herb', layer: 'herbaceous', climates: ['temperate', 'subtropical', 'tropical'], companions: ['basil', 'oregano', 'carrot', 'tomato'], antagonists: ['fennel'], spacing: 0.4, harvestMonths: [7, 8, 9, 10], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Needs warmth. Good container plant.' },
	{ id: 'beans', name: 'Beans (Bush/Pole)', scientificName: 'Phaseolus vulgaris', category: 'herb', layer: 'herbaceous', climates: ['temperate', 'subtropical', 'tropical'], companions: ['corn', 'squash', 'nasturtium', 'oregano'], antagonists: ['garlic', 'chives', 'fennel'], spacing: 0.15, harvestMonths: [7, 8, 9], edible: true, nitrogenFixer: true, dynamicAccumulator: false, notes: 'Nitrogen fixer. Three Sisters companion.' },
	{ id: 'peas', name: 'Peas', scientificName: 'Pisum sativum', category: 'herb', layer: 'herbaceous', climates: ['temperate'], companions: ['carrot', 'corn', 'cucumber', 'lettuce'], antagonists: ['garlic', 'chives'], spacing: 0.1, harvestMonths: [5, 6, 7], edible: true, nitrogenFixer: true, dynamicAccumulator: false, notes: 'Cool season. Good green manure.' },
	{ id: 'corn', name: 'Corn / Maize', scientificName: 'Zea mays', category: 'grass', layer: 'herbaceous', climates: ['temperate', 'subtropical', 'tropical'], companions: ['beans', 'squash', 'cucumber'], antagonists: ['tomato'], spacing: 0.3, harvestMonths: [8, 9], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Three Sisters: corn, beans, squash.' },
	{ id: 'squash', name: 'Squash / Pumpkin', scientificName: 'Cucurbita spp.', category: 'herb', layer: 'herbaceous', climates: ['temperate', 'subtropical', 'tropical'], companions: ['corn', 'beans', 'nasturtium', 'borage'], antagonists: [], spacing: 1, harvestMonths: [8, 9, 10], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Living mulch. Three Sisters companion.' },
	{ id: 'cucumber', name: 'Cucumber', scientificName: 'Cucumis sativus', category: 'herb', layer: 'herbaceous', climates: ['temperate', 'subtropical', 'tropical'], companions: ['corn', 'beans', 'dill', 'nasturtium'], antagonists: ['sage'], spacing: 0.5, harvestMonths: [7, 8, 9], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Needs consistent moisture.' },
	{ id: 'lettuce', name: 'Lettuce', scientificName: 'Lactuca sativa', category: 'herb', layer: 'herbaceous', climates: ['temperate', 'subtropical'], companions: ['carrot', 'strawberry', 'chives', 'peas'], antagonists: [], spacing: 0.2, harvestMonths: [4, 5, 6, 7, 8, 9, 10], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Cool season. Shade-tolerant.' },
	{ id: 'cabbage', name: 'Cabbage / Brassicas', scientificName: 'Brassica oleracea', category: 'herb', layer: 'herbaceous', climates: ['temperate', 'subtropical'], companions: ['dill', 'sage', 'thyme', 'mint'], antagonists: ['strawberry'], spacing: 0.4, harvestMonths: [5, 6, 9, 10, 11], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Includes broccoli, kale, cauliflower.' },
	{ id: 'carrot', name: 'Carrot', scientificName: 'Daucus carota', category: 'root', layer: 'root', climates: ['temperate', 'subtropical'], companions: ['tomato', 'chives', 'rosemary', 'sage', 'peas', 'lettuce'], antagonists: ['dill', 'fennel'], spacing: 0.08, harvestMonths: [6, 7, 8, 9, 10], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Loose, deep soil. Interplant with alliums.' },

	// ===== GROUNDCOVERS =====
	{ id: 'strawberry', name: 'Strawberry', scientificName: 'Fragaria × ananassa', category: 'groundcover', layer: 'groundcover', climates: ['temperate', 'subtropical'], companions: ['borage', 'lettuce', 'thyme', 'blueberry'], antagonists: ['cabbage'], spacing: 0.3, harvestMonths: [5, 6, 7], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Good living mulch under fruit trees.' },
	{ id: 'clover', name: 'White Clover', scientificName: 'Trifolium repens', category: 'groundcover', layer: 'groundcover', climates: ['temperate', 'subtropical'], companions: ['apple', 'pear', 'plum', 'blueberry'], antagonists: [], spacing: 0.1, edible: false, nitrogenFixer: true, dynamicAccumulator: false, notes: 'Living mulch. Nitrogen fixer. Bee forage.' },
	{ id: 'sweet-potato', name: 'Sweet Potato', scientificName: 'Ipomoea batatas', category: 'groundcover', layer: 'groundcover', climates: ['tropical', 'subtropical'], companions: ['banana', 'moringa', 'pigeon-pea', 'avocado'], antagonists: [], spacing: 0.3, harvestMonths: [10, 11, 12], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Vigorous groundcover. Suppresses weeds.' },
	{ id: 'taro', name: 'Taro', scientificName: 'Colocasia esculenta', category: 'root', layer: 'root', climates: ['tropical', 'subtropical'], companions: ['banana', 'coconut', 'katuk'], antagonists: [], spacing: 0.5, harvestMonths: [9, 10, 11], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Needs wet soil. Good for bog gardens.' },
	{ id: 'fern', name: 'Fern', scientificName: 'Various spp.', category: 'groundcover', layer: 'groundcover', climates: ['temperate', 'subtropical', 'tropical'], companions: ['blueberry'], antagonists: [], spacing: 0.4, edible: false, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Shade-loving groundcover. Mulch source.' },

	// ===== VINES =====
	{ id: 'grape', name: 'Grape', scientificName: 'Vitis vinifera', category: 'vine', layer: 'vine', climates: ['temperate', 'subtropical', 'arid'], companions: ['clover', 'garlic', 'chives'], antagonists: [], spacing: 2, harvestMonths: [8, 9, 10], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Needs trellis or pergola. Many varieties.' },
	{ id: 'passionfruit', name: 'Passionfruit', scientificName: 'Passiflora edulis', category: 'vine', layer: 'vine', climates: ['tropical', 'subtropical'], companions: ['banana', 'comfrey'], antagonists: [], spacing: 3, harvestMonths: [1, 2, 3, 11, 12], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Vigorous grower. Needs sturdy trellis.' },
	{ id: 'kiwi', name: 'Kiwi', scientificName: 'Actinidia deliciosa', category: 'vine', layer: 'vine', climates: ['temperate', 'subtropical'], companions: ['comfrey', 'clover'], antagonists: [], spacing: 3, harvestMonths: [10, 11], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Male + female needed. Strong trellis.' },
	{ id: 'chayote', name: 'Chayote', scientificName: 'Sechium edule', category: 'vine', layer: 'vine', climates: ['tropical', 'subtropical'], companions: ['corn', 'beans'], antagonists: [], spacing: 3, harvestMonths: [9, 10, 11], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Prolific producer. Edible tubers too.' },

	// ===== NITROGEN FIXERS =====
	{ id: 'lucerne', name: 'Lucerne / Alfalfa', scientificName: 'Medicago sativa', category: 'herb', layer: 'herbaceous', climates: ['temperate', 'arid', 'subtropical'], companions: [], antagonists: [], spacing: 0.15, edible: false, nitrogenFixer: true, dynamicAccumulator: true, notes: 'Deep-rooted nitrogen fixer. Chop-and-drop.' },
	{ id: 'lupin', name: 'Lupin', scientificName: 'Lupinus spp.', category: 'herb', layer: 'herbaceous', climates: ['temperate'], companions: [], antagonists: [], spacing: 0.3, edible: false, nitrogenFixer: true, dynamicAccumulator: false, notes: 'Green manure. Beautiful flowers.' },

	// ===== ARID SPECIALISTS =====
	{ id: 'prickly-pear', name: 'Prickly Pear', scientificName: 'Opuntia ficus-indica', category: 'shrub', layer: 'shrub', climates: ['arid', 'subtropical'], companions: ['olive', 'pomegranate'], antagonists: [], spacing: 2, harvestMonths: [7, 8, 9], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Extremely drought-tolerant. Living fence.' },
	{ id: 'aloe', name: 'Aloe Vera', scientificName: 'Aloe barbadensis', category: 'herb', layer: 'herbaceous', climates: ['arid', 'subtropical', 'tropical'], companions: ['lavender', 'rosemary'], antagonists: [], spacing: 0.4, edible: false, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Medicinal. Fire-resistant barrier.' },
	{ id: 'jojoba', name: 'Jojoba', scientificName: 'Simmondsia chinensis', category: 'shrub', layer: 'shrub', climates: ['arid'], companions: ['olive', 'pomegranate'], antagonists: [], spacing: 3, edible: false, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Extremely drought-tolerant. Oil crop.' },
	{ id: 'date-palm', name: 'Date Palm', scientificName: 'Phoenix dactylifera', category: 'tree', layer: 'canopy', climates: ['arid', 'subtropical'], companions: ['pomegranate', 'olive', 'lucerne'], antagonists: [], spacing: 8, harvestMonths: [9, 10, 11], edible: true, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Hot arid climates. Male + female needed.' },
	{ id: 'mesquite', name: 'Mesquite', scientificName: 'Prosopis spp.', category: 'tree', layer: 'canopy', climates: ['arid'], companions: ['prickly-pear', 'jojoba'], antagonists: [], spacing: 6, harvestMonths: [7, 8], edible: true, nitrogenFixer: true, dynamicAccumulator: false, notes: 'Nitrogen-fixing tree. Pods are edible flour source.' },

	// ===== ADDITIONAL USEFUL PLANTS =====
	{ id: 'rose', name: 'Rose', scientificName: 'Rosa spp.', category: 'shrub', layer: 'shrub', climates: ['temperate', 'subtropical'], companions: ['garlic', 'chives', 'parsley'], antagonists: [], spacing: 1, edible: false, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Hips are edible. Companion for garlic.' },
	{ id: 'sunflower', name: 'Sunflower', scientificName: 'Helianthus annuus', category: 'herb', layer: 'herbaceous', climates: ['temperate', 'subtropical', 'arid'], companions: ['corn', 'cucumber', 'squash'], antagonists: [], spacing: 0.4, harvestMonths: [8, 9, 10], edible: true, nitrogenFixer: false, dynamicAccumulator: true, notes: 'Attracts pollinators. Seeds for food.' },
	{ id: 'bamboo', name: 'Clumping Bamboo', scientificName: 'Bambusa spp.', category: 'grass', layer: 'canopy', climates: ['tropical', 'subtropical'], companions: [], antagonists: [], spacing: 3, edible: false, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Windbreak. Building material. Use CLUMPING only.' },
	{ id: 'vetiver', name: 'Vetiver Grass', scientificName: 'Chrysopogon zizanioides', category: 'grass', layer: 'herbaceous', climates: ['tropical', 'subtropical', 'arid'], companions: [], antagonists: [], spacing: 0.15, edible: false, nitrogenFixer: false, dynamicAccumulator: false, notes: 'Erosion control. Deep roots. Contour hedgerow.' },
];

/** Search plants by name, category, or climate. */
export function searchPlants(query: string, climate?: ClimateType): Plant[] {
	const q = query.toLowerCase();
	return plants.filter((p) => {
		const matchesQuery = !q || p.name.toLowerCase().includes(q)
			|| p.scientificName.toLowerCase().includes(q)
			|| p.category.includes(q)
			|| p.layer.includes(q);
		const matchesClimate = !climate || p.climates.includes(climate);
		return matchesQuery && matchesClimate;
	});
}

/** Get a plant by ID. */
export function getPlant(id: string): Plant | undefined {
	return plants.find((p) => p.id === id);
}

/** Get plants by layer. */
export function getPlantsByLayer(layer: Plant['layer']): Plant[] {
	return plants.filter((p) => p.layer === layer);
}
